import {Arrays, Edges, Paths} from '#codec'
import {
  allLeavesFold,
  countOfFold,
  degreeFold,
  descendantCountFold,
  filterLeavesFold,
  filterNodesFold,
  growLeavesFold,
  includesFold,
  levelsFold,
  maximumDegreeFold,
  maximumHeightFold,
  numericMaxFold,
  numericMinFold,
  numericProductFold,
  numericSumFold,
  postOrderFold,
  preOrderFold,
  unzipFold,
  unzipTheseFold,
} from '#ops'
import {
  eqvFold,
  everyFold,
  flattenFold,
  monoidFold,
  predicateFold,
  someFold,
  xorFold,
} from '#tree'

/**
 * All folds in a single place.
 * @category folds
 */
export const folds = {
  allLeaves: allLeavesFold,
  arrays: Arrays.unsafeEncodeFold,
  boolean: predicateFold,
  countOf: countOfFold,
  degree: degreeFold,
  descendantCount: descendantCountFold,
  edges: Edges.encodeFold,
  eqv: eqvFold,
  every: everyFold,
  filterLeaves: filterLeavesFold,
  filterNodes: filterNodesFold,
  flatten: flattenFold,
  growLeaves: growLeavesFold,
  includes: includesFold,
  levels: levelsFold,
  maximumDegree: maximumDegreeFold,
  maximumHeight: maximumHeightFold,
  monoid: monoidFold,
  nodeOrdinalFold: maximumHeightFold,
  numericMax: numericMaxFold,
  numericMin: numericMinFold,
  numericProduct: numericProductFold,
  numericSum: numericSumFold,
  paths: Paths.pathListFold,
  postOrder: postOrderFold,
  predicate: predicateFold,
  preOrder: preOrderFold,
  some: someFold,
  unzip: unzipFold,
  unzipTheseFold,
  xor: xorFold,
}
